controller_list:
  - name: fake_robot_Base_controller
    joints:
      []
  - name: fake_left_pa10_controller
    joints:
      - l_shoulder_roll_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint