controller_list:
  - name: fake_l_arm_controller
    joints:
      - pa10_green_shoulder_roll_joint
      - pa10_green_shoulder_lift_joint
      - pa10_green_upper_arm_roll_joint
      - pa10_green_elbow_flex_joint
      - pa10_green_forearm_roll_joint
      - pa10_green_wrist_flex_joint
      - pa10_green_wrist_roll_joint
  - name: fake_whole_controller
    joints:
      - pa10_green_shoulder_roll_joint
      - pa10_green_shoulder_lift_joint
      - pa10_green_upper_arm_roll_joint
      - pa10_green_elbow_flex_joint
      - pa10_green_forearm_roll_joint
      - pa10_green_wrist_flex_joint
      - pa10_green_wrist_roll_joint
  - name: fake_l_hand_controller
    joints:
      - l_allegro_joint_0
      - l_allegro_joint_1
      - l_allegro_joint_2
      - l_allegro_joint_3
      - l_allegro_joint_12
      - l_allegro_joint_13
      - l_allegro_joint_14
      - l_allegro_joint_15
      - l_allegro_joint_4
      - l_allegro_joint_5
      - l_allegro_joint_6
      - l_allegro_joint_7
      - l_allegro_joint_8
      - l_allegro_joint_9
      - l_allegro_joint_10
      - l_allegro_joint_11
  - name: fake_l_armpalm_controller
    joints:
      - pa10_green_shoulder_roll_joint
      - pa10_green_shoulder_lift_joint
      - pa10_green_upper_arm_roll_joint
      - pa10_green_elbow_flex_joint
      - pa10_green_forearm_roll_joint
      - pa10_green_wrist_flex_joint
      - pa10_green_wrist_roll_joint
  - name: fake_l_first_finger_controller
    joints:
      - l_allegro_joint_0
      - l_allegro_joint_1
      - l_allegro_joint_2
      - l_allegro_joint_3
  - name: fake_l_middle_finger_controller
    joints:
      - l_allegro_joint_4
      - l_allegro_joint_5
      - l_allegro_joint_6
      - l_allegro_joint_7
  - name: fake_l_ring_finger_controller
    joints:
      - l_allegro_joint_8
      - l_allegro_joint_9
      - l_allegro_joint_10
      - l_allegro_joint_11
  - name: fake_l_thumb_controller
    joints:
      - l_allegro_joint_12
      - l_allegro_joint_13
      - l_allegro_joint_14
      - l_allegro_joint_15
  - name: fake_l_fingers_controller
    joints:
      - l_allegro_joint_0
      - l_allegro_joint_1
      - l_allegro_joint_2
      - l_allegro_joint_3
      - l_allegro_joint_12
      - l_allegro_joint_13
      - l_allegro_joint_14
      - l_allegro_joint_15
      - l_allegro_joint_4
      - l_allegro_joint_5
      - l_allegro_joint_6
      - l_allegro_joint_7
      - l_allegro_joint_8
      - l_allegro_joint_9
      - l_allegro_joint_10
      - l_allegro_joint_11
  - name: fake_l_three_finger_grasp_controller
    joints:
      - l_allegro_joint_0
      - l_allegro_joint_1
      - l_allegro_joint_2
      - l_allegro_joint_3
      - l_allegro_joint_12
      - l_allegro_joint_13
      - l_allegro_joint_14
      - l_allegro_joint_15
      - l_allegro_joint_4
      - l_allegro_joint_5
      - l_allegro_joint_6
      - l_allegro_joint_7