controller_list:
  - name: fake_l_arm_controller
    joints:
      - pa10_green_shoulder_roll_joint
      - pa10_green_shoulder_lift_joint
      - pa10_green_upper_arm_roll_joint
      - pa10_green_elbow_flex_joint
      - pa10_green_forearm_roll_joint
      - pa10_green_wrist_flex_joint
      - pa10_green_wrist_roll_joint
  - name: fake_r_arm_controller
    joints:
      - pa10_blue_shoulder_roll_joint
      - pa10_blue_shoulder_lift_joint
      - pa10_blue_upper_arm_roll_joint
      - pa10_blue_elbow_flex_joint
      - pa10_blue_forearm_roll_joint
      - pa10_blue_wrist_flex_joint
      - pa10_blue_wrist_roll_joint
  - name: fake_whole_controller
    joints:
      - pa10_green_shoulder_roll_joint
      - pa10_green_shoulder_lift_joint
      - pa10_green_upper_arm_roll_joint
      - pa10_green_elbow_flex_joint
      - pa10_green_forearm_roll_joint
      - pa10_green_wrist_flex_joint
      - pa10_green_wrist_roll_joint
      - pa10_blue_shoulder_roll_joint
      - pa10_blue_shoulder_lift_joint
      - pa10_blue_upper_arm_roll_joint
      - pa10_blue_elbow_flex_joint
      - pa10_blue_forearm_roll_joint
      - pa10_blue_wrist_flex_joint
      - pa10_blue_wrist_roll_joint
  - name: fake_l_hand_controller
    joints:
      - l_allegro_joint_0.0
      - l_allegro_joint_1.0
      - l_allegro_joint_2.0
      - l_allegro_joint_3.0
      - l_allegro_joint_12.0
      - l_allegro_joint_13.0
      - l_allegro_joint_14.0
      - l_allegro_joint_15.0
      - l_allegro_joint_4.0
      - l_allegro_joint_5.0
      - l_allegro_joint_6.0
      - l_allegro_joint_7.0
      - l_allegro_joint_8.0
      - l_allegro_joint_9.0
      - l_allegro_joint_10.0
      - l_allegro_joint_11.0
  - name: fake_r_hand_controller
    joints:
      - WRJ2
      - WRJ1
      - FFJ4
      - FFJ3
      - FFJ2
      - FFJ1
      - LFJ5
      - LFJ4
      - LFJ3
      - LFJ2
      - LFJ1
      - MFJ4
      - MFJ3
      - MFJ2
      - MFJ1
      - RFJ4
      - RFJ3
      - RFJ2
      - RFJ1
      - THJ5
      - THJ4
      - THJ3
      - THJ2
      - THJ1
  - name: fake_l_armpalm_controller
    joints:
      - pa10_green_shoulder_roll_joint
      - pa10_green_shoulder_lift_joint
      - pa10_green_upper_arm_roll_joint
      - pa10_green_elbow_flex_joint
      - pa10_green_forearm_roll_joint
      - pa10_green_wrist_flex_joint
      - pa10_green_wrist_roll_joint
  - name: fake_r_armpalm_controller
    joints:
      - pa10_blue_shoulder_roll_joint
      - pa10_blue_shoulder_lift_joint
      - pa10_blue_upper_arm_roll_joint
      - pa10_blue_elbow_flex_joint
      - pa10_blue_forearm_roll_joint
      - pa10_blue_wrist_flex_joint
      - pa10_blue_wrist_roll_joint
      - WRJ2
      - WRJ1
  - name: fake_r_first_finger_controller
    joints:
      - FFJ4
      - FFJ3
      - FFJ2
      - FFJ1
  - name: fake_r_middle_finger_controller
    joints:
      - MFJ4
      - MFJ3
      - MFJ2
      - MFJ1
  - name: fake_r_ring_finger_controller
    joints:
      - RFJ4
      - RFJ3
      - RFJ2
      - RFJ1
  - name: fake_r_little_finger_controller
    joints:
      - LFJ5
      - LFJ4
      - LFJ3
      - LFJ2
      - LFJ1
  - name: fake_r_thumb_controller
    joints:
      - THJ5
      - THJ4
      - THJ3
      - THJ2
      - THJ1
  - name: fake_r_fingers_controller
    joints:
      - FFJ4
      - FFJ3
      - FFJ2
      - FFJ1
      - LFJ5
      - LFJ4
      - LFJ3
      - LFJ2
      - LFJ1
      - MFJ4
      - MFJ3
      - MFJ2
      - MFJ1
      - RFJ4
      - RFJ3
      - RFJ2
      - RFJ1
      - THJ5
      - THJ4
      - THJ3
      - THJ2
      - THJ1
  - name: fake_l_first_finger_controller
    joints:
      - l_allegro_joint_0.0
      - l_allegro_joint_1.0
      - l_allegro_joint_2.0
      - l_allegro_joint_3.0
  - name: fake_l_middle_finger_controller
    joints:
      - l_allegro_joint_4.0
      - l_allegro_joint_5.0
      - l_allegro_joint_6.0
      - l_allegro_joint_7.0
  - name: fake_l_ring_finger_controller
    joints:
      - l_allegro_joint_8.0
      - l_allegro_joint_9.0
      - l_allegro_joint_10.0
      - l_allegro_joint_11.0
  - name: fake_l_thumb_controller
    joints:
      - l_allegro_joint_12.0
      - l_allegro_joint_13.0
      - l_allegro_joint_14.0
      - l_allegro_joint_15.0
  - name: fake_l_fingers_controller
    joints:
      - l_allegro_joint_0.0
      - l_allegro_joint_1.0
      - l_allegro_joint_2.0
      - l_allegro_joint_3.0
      - l_allegro_joint_12.0
      - l_allegro_joint_13.0
      - l_allegro_joint_14.0
      - l_allegro_joint_15.0
      - l_allegro_joint_4.0
      - l_allegro_joint_5.0
      - l_allegro_joint_6.0
      - l_allegro_joint_7.0
      - l_allegro_joint_8.0
      - l_allegro_joint_9.0
      - l_allegro_joint_10.0
      - l_allegro_joint_11.0