joint_names: [r_shoulder_roll_joint,r_shoulder_lift_joint,r_upper_arm_roll_joint,r_elbow_flex_joint,r_forearm_roll_joint,r_wrist_flex_joint,r_wrist_roll_joint]
r_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints: [r_shoulder_roll_joint,r_shoulder_lift_joint,r_upper_arm_roll_joint,r_elbow_flex_joint,r_forearm_roll_joint,r_wrist_flex_joint,r_wrist_roll_joint]
  gains:
    r_shoulder_roll_joint: {p: 2400.0, d: 18.0, i: 800.0, i_clamp: 4.0}
    r_shoulder_lift_joint: {p: 1200.0, d: 10.0, i: 700.0, i_clamp: 4.0}
    r_upper_arm_roll_joint: {p: 1000.0, d: 6.0, i: 600.0, i_clamp: 4.0}
    r_elbow_flex_joint: {p: 700.0, d: 4.0, i: 450, i_clamp: 4.0}
    r_forearm_roll_joint: {p: 300.0, d: 6.0, i: 300, i_clamp: 2.0}
    r_wrist_flex_joint: {p: 300.0, d: 4.0, i: 300, i_clamp: 2.0}
    r_wrist_roll_joint: {p: 300.0, d: 4.0, i: 300, i_clamp: 2.0}
  constraints:
    goal_time: 0.6
    r_shoulder_roll_link:
      goal: 0.02
    r_shoulder_lift_joint:
      goal: 0.02
    r_upper_arm_roll_joint:
      goal: 0.02
    r_elbow_flex_joint:
      goal: 0.02
    r_forearm_roll_joint:
      goal: 0.02
    r_wrist_flex_joint:
      goal: 0.02
    r_wrist_roll_joint:
      goal: 0.02

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50