joint_names: [profiles_joint,base_down_joint,base_up_joint,bearing_under_joint,bearing_joint,bearing_above_joint,trunk_left_joint,l_shoulder_roll_joint,l_shoulder_lift_joint,l_upper_arm_roll_joint,l_elbow_flex_joint,l_forearm_roll_joint,l_wrist_flex_joint,l_wrist_roll_joint]

l_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints: [l_shoulder_roll_joint,l_shoulder_lift_joint,l_upper_arm_roll_joint,l_elbow_flex_joint,l_forearm_roll_joint,l_wrist_flex_joint,l_wrist_roll_joint]
  gains:
    l_shoulder_roll_joint: {p: 2400.0, d: 18.0, i: 800.0, i_clamp: 4.0}
    l_shoulder_lift_joint: {p: 1200.0, d: 10.0, i: 700.0, i_clamp: 4.0}
    l_upper_arm_roll_joint: {p: 1000.0, d: 6.0, i: 600.0, i_clamp: 4.0}
    l_elbow_flex_joint: {p: 700.0, d: 4.0, i: 450, i_clamp: 4.0}
    l_forearm_roll_joint: {p: 300.0, d: 6.0, i: 300, i_clamp: 2.0}
    l_wrist_flex_joint: {p: 300.0, d: 4.0, i: 300, i_clamp: 2.0}
    l_wrist_roll_joint: {p: 300.0, d: 4.0, i: 300, i_clamp: 2.0}
  constraints:
    goal_time: 0.6
    l_shoulder_roll_joint:
      goal: 0.02
    l_shoulder_lift_joint:
      goal: 0.02
    l_upper_arm_roll_joint:
      goal: 0.02
    l_elbow_flex_joint:
      goal: 0.02
    l_forearm_roll_joint:
      goal: 0.02
    l_wrist_flex_joint:
      goal: 0.02
    l_wrist_roll_joint:
      goal: 0.02

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50