joint_names: [l_shoulder_roll_joint,l_shoulder_lift_joint,
  l_upper_arm_roll_joint,l_elbow_flex_joint,l_forearm_roll_joint,
  l_wrist_flex_joint,l_wrist_roll_joint,l_jr3_joint,
  l_allegro_joint_0,l_allegro_joint_1,l_allegro_joint_2,l_allegro_joint_3,
  l_allegro_joint_4,l_allegro_joint_5,l_allegro_joint_6,l_allegro_joint_7,
  l_allegro_joint_8,l_allegro_joint_9,l_allegro_joint_10,l_allegro_joint_11,
  l_allegro_joint_12,l_allegro_joint_13,l_allegro_joint_14,l_allegro_joint_15]

l_arm_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints: [l_shoulder_roll_joint,l_shoulder_lift_joint,
    l_upper_arm_roll_joint,l_elbow_flex_joint,l_forearm_roll_joint,
    l_wrist_flex_joint,l_wrist_roll_joint]
  gains:
    l_shoulder_roll_joint: {p: 2400.0, d: 18.0, i: 800.0, i_clamp: 4.0}
    l_shoulder_lift_joint: {p: 1200.0, d: 10.0, i: 700.0, i_clamp: 4.0}
    l_upper_arm_roll_joint: {p: 1000.0, d: 6.0, i: 600.0, i_clamp: 4.0}
    l_elbow_flex_joint: {p: 700.0, d: 4.0, i: 450, i_clamp: 4.0}
    l_forearm_roll_joint: {p: 300.0, d: 6.0, i: 300, i_clamp: 2.0}
    l_wrist_flex_joint: {p: 300.0, d: 4.0, i: 300, i_clamp: 2.0}
    l_wrist_roll_joint: {p: 300.0, d: 4.0, i: 300, i_clamp: 2.0}
  constraints:
    goal_time: 0.6
    l_shoulder_roll_joint:
      goal: 0.02
    l_shoulder_lift_joint:
      goal: 0.02
    l_upper_arm_roll_joint:
      goal: 0.02
    l_elbow_flex_joint:
      goal: 0.02
    l_forearm_roll_joint:
      goal: 0.02
    l_wrist_flex_joint:
      goal: 0.02
    l_wrist_roll_joint:
      goal: 0.02

l_allegro_controller:
  type: "effort_controllers/JointTrajectoryController"
  joints: [l_allegro_joint_0,l_allegro_joint_1,l_allegro_joint_2,l_allegro_joint_3,
  l_allegro_joint_4,l_allegro_joint_5,l_allegro_joint_6,l_allegro_joint_7,
  l_allegro_joint_8,l_allegro_joint_9,l_allegro_joint_10,l_allegro_joint_11,
  l_allegro_joint_12,l_allegro_joint_13,l_allegro_joint_14,l_allegro_joint_15]
  gains:
    l_allegro_joint_0: {p: 10000.0, d: 1000.0}
    l_allegro_joint_1: {p: 10000.0, d: 1000.0}
    l_allegro_joint_2: {p: 10000.0, d: 1000.0}
    l_allegro_joint_3: {p: 10000.0, d: 1000.0}
    l_allegro_joint_4: {p: 10000.0, d: 1000.0}
    l_allegro_joint_5: {p: 10000.0, d: 1000.0}
    l_allegro_joint_6: {p: 10000.0, d: 1000.0}
    l_allegro_joint_7: {p: 10000.0, d: 1000.0}
    l_allegro_joint_8: {p: 10000.0, d: 1000.0}
    l_allegro_joint_9: {p: 10000.0, d: 1000.0}
    l_allegro_joint_10: {p: 10000.0, d: 1000.0}
    l_allegro_joint_11: {p: 10000.0, d: 1000.0}
    l_allegro_joint_12: {p: 10000.0, d: 1000.0}
    l_allegro_joint_13: {p: 10000.0, d: 1000.0}
    l_allegro_joint_14: {p: 10000.0, d: 1000.0}
    l_allegro_joint_15: {p: 10000.0, d: 1000.0}

joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50