<?xml version="1.0"?>

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
      xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
      xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
      xmlns:xacro="http://ros.org/wiki/xacro">
  
  <xacro:include filename="$(find aurobot_description)/urdf/sensors/kinect_camera.gazebo.xacro"/>

  <property name="ir_depth_rgb_offset_y" value="0.01"/> <!-- FIXME: what is this offset? -->

  <xacro:macro name="kinect_camera" params="name ns">
    <link name="${name}_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
                 iyy="0.01"  iyz="0.0"
                 izz="0.01"/>
      </inertial>
      <visual>
        <origin xyz="0.0325 0 0.057" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://aurobot_description/meshes/sensors/kinect/kinect.dae" scale="0.001 0.001 0.001"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0325 0 0.057" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://aurobot_description/meshes/sensors/kinect/kinect.dae" scale="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_joint" type="fixed">
      <origin xyz="0.032267 0.0125 0.062453" rpy="0 0 0"/>
      <parent link="${name}_link"/>
      <child link="${name}_kinect_depth_link"/>
    </joint>

    <!-- kinect ir sensor physical attachment -->
    <link name="${name}_kinect_depth_link">
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
                 iyy="0.01"  iyz="0.0"
                 izz="0.01"/>
      </inertial>
      <visual>
        <geometry>
          <sphere radius="0.0005"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <sphere radius="0.0005"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_kinect_depth_opt_joint" type="fixed">
      <origin xyz="${cal_kinect_x}            ${cal_kinect_y + ir_depth_rgb_offset_y}         ${cal_kinect_z}"
              rpy="${-M_PI/2+cal_kinect_roll} ${0.0+cal_kinect_pitch} ${-M_PI/2+cal_kinect_yaw}"/>
      <parent link="${name}_kinect_depth_link"/>
      <child link="${name}_kinect_depth_optical_frame"/>
    </joint>
    <joint name="${name}_kinect_depth_rgb_joint" type="fixed">
      <origin xyz="0 -0.03 0" rpy="0 0 0"/>
      <parent link="${name}_kinect_depth_link"/>
      <child link="${name}_kinect_rgb_link"/>
    </joint>
    
    <!-- kinect ir sensor frame -->
    <link name="${name}_kinect_depth_optical_frame"/>

    <!-- kinect rgb sensor physical attachment -->
    <link name="${name}_kinect_rgb_link" >
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.01"  ixy="0.0"  ixz="0.0"
                 iyy="0.01"  iyz="0.0"
                 izz="0.01"/>
      </inertial>
      <visual>
        <origin xyz="0.0325 0 0.127" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.0005"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0325 0 0.127" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.0005"/>
        </geometry>
      </collision>
    </link>
    <joint name="${name}_kinect_rgb_opt_joint" type="fixed">
      <origin xyz="${cal_kinect_x}            ${cal_kinect_y}         ${cal_kinect_z}"
              rpy="${-M_PI/2+cal_kinect_roll} ${0.0+cal_kinect_pitch} ${-M_PI/2+cal_kinect_yaw}"/>
      <parent link="${name}_kinect_rgb_link"/>
      <child link="${name}_kinect_rgb_optical_frame"/>
    </joint>

    <!-- kinect rgb sensor frame -->
    <link name="${name}_kinect_rgb_optical_frame"/>
    
    <!-- gazebo extensions -->
    <xacro:kinect_depth_gazebo name="${name}" link_name="${name}_kinect_depth_link" frame_name="${name}_kinect_depth_optical_frame" ns="${ns}" camera_name="camera"/>
    <xacro:kinect_rgb_gazebo name="${name}" link_name="${name}_kinect_rgb_link" frame_name="${name}_kinect_rgb_optical_frame" ns="${ns}" camera_name="camera"/>
  </xacro:macro>
</robot>